/*
 * startup.cc
 *
 *  Created on: Apr. 22, 2020
 *      Author: solomon
 */

#include "startup.h"
#include <string>

void initHelpers(std::ostream& file){
	initializeHeap(file);
	initializeIO(file);
}

void initializeHeap(std::ostream& file){
	// procedures for using heap memory. We read
	// in the procedures from an assembly file and
	// copy them over to our autogenerated assembly.

	// Default heap file "heap.asm"

	std::fstream heap_asm("heap.asm");
	std::string line = "";

	while(getline(heap_asm, line)){
		file << line << std::endl;
	}
	heap_asm.close();

}

void initializeIO(std::ostream& file){
	// Procedure for input and output
	// This include the procedure for converting
	// ascii to integers and for printing
	// integers to stdout.

	// Default IO file "io.asm"

	std::fstream heap_asm("io.asm");
	std::string line = "";

	while(getline(heap_asm, line)){
		file << line << std::endl;
	}
	heap_asm.close();
}


